FROM golang

ENV PROJECT_DIR=$GOPATH/src/github.com/frosenberg/go-cloud-stream-modules/go-httpclient-processor

RUN mkdir -p $PROJECT_DIR
ADD . $PROJECT_DIR
WORKDIR $PROJECT_DIR

RUN make buildgo && \
    cp $PROJECT_DIR/main /main

CMD ["/bin/bash"]
